---
title: "Documenting R Code"
author: "Kelly Sovacool"
date: "5/21/2019"
output: 
    ioslides_presentation:
        widescreen: true
---
```{R setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

## Why document your code?

- Reproducibility
- FAIR data principles: findable, accessible, **interopable**, **reusable**
- Make it usable for other scientists -- including future you!

## Ten simple rules for documenting scientific software

### Excerpted from [Lee et al. 2018](https://doi.org/10.1371/journal.pcbi.1006561):

- Write comments as you code.
- Include a README file with basic information.
- Version control your documentation.
- Use automated documentation tools.
- Write error messages that provide solutions or point to your documentation.

## What not to document

- "Document Design and Purpose, Not Mechanics" - [Wilson et al. 2014](Wilson G, Aruliah DA, Brown CT, Chue Hong NP, Davis M, Guy RT, et al. (2014) Best Practices for Scientific Computing. PLoS Biol 12(1): e1001745. https://doi.org/10.1371/journal.pbio.1001745)
- In other words, "Why, not how".
- Don't do this:
    ```{R}
    i <- i + 1  # increment `i` by 1
    ```
- Try to write code that is self-documenting.
    - Use descriptive variable names.
    
## What to document

- No code is fully self-documenting. 
- You should document:
    - modules
    - datasets
    - functions
    - classes
    - any tricky lines of code

## How (specifics for R)

### The bare minimum:

Include a comment at the top of your R script to briefly describe what it does at a high level. 

    ```{R}
    # Generate plots from mothur sensspec files for comparing clustering algorithms.
    ```

---

### Best practices:

For any project with R scripts:
    - Write comments alongside your code with `roxygen2` syntax.
    - Make your project a package with `usethis` & `devtools`.
For packages you release into the wild:
    - Write a vignette with `R Markdown`.
    - Create a website with `pkgdown`.

---

## Activity

Let's document a script from the [Riffomonas minimalR](http://www.riffomonas.org/minimalR/06_line_plots.html) tutorial!

1. module
1. dataset
    - `raw_data/baxter.metadata.xlsx`
1. functions
    - `get_metadata`
    - `get_bmi`
    - `get_bmi_category`
    - `is_obese`
1. error message

---

### Instructions

1. Clone this repo
    ```{bash}
    git clone https://github.com/SchlossLab/documenting-R
    ```
1. Checkout a new branch
    ```{bash}
    git checkout -b descriptive-branch-name
    ```
1. After modifying your part, commit your changes
    ```{bash}
    git add .
    git commit -m "descriptive commit message"
    ```
1. Push your changes
    ```{bash}
    git push -u origin descriptive-branch-name
    ```

## Demo 

```{R}
library(usethis)
create_package(file.path(getwd()), 'documentingR')
```

## Additional Reading

- [R Packages](http://r-pkgs.had.co.nz/man.html) - Hadley Wickham
- [pkgdown](https://pkgdown.r-lib.org/): build a website for your R package
- [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/documentation.html) - Roger Peng, Sean Kross, & Brooke Anderson

