---
title: "Documenting R Code"
author: "Kelly Sovacool"
date: "5/21/2019"
output: 
    ioslides_presentation:
        widescreen: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

## Why document your code?

- Reproducibility
- FAIR data principles: findable, accessible, **interopable**, **reusable**
- Make it usable for other scientists -- including future you!

## Ten simple rules for documenting scientific software

### Excerpted from [Lee et al. 2018](https://doi.org/10.1371/journal.pcbi.1006561):

- Write comments as you code.
- Include a README file with basic information.
- Version control your documentation.
- Use automated documentation tools.
- Write error messages that provide solutions or point to your documentation.

## What not to document

- "Document Design and Purpose, Not Mechanics" - [Wilson et al. 2014](Wilson G, Aruliah DA, Brown CT, Chue Hong NP, Davis M, Guy RT, et al. (2014) Best Practices for Scientific Computing. PLoS Biol 12(1): e1001745. https://doi.org/10.1371/journal.pbio.1001745)
- In other words, "Why, not how".
- Don't do this:
    ```{R}
    i <- i + 1  # increment `i` by 1
    ```

## What to document

- Try to write code that is self-documenting.
    - Use descriptive variable names.
- But no code is fully self-documenting. You should document:
    - modules
    - datasets
    - functions
    - classes
    - any tricky lines of code

## How (specifics for R)

### The bare minimum:

Include a comment at the top of your R script to briefly describe what it does at a high level. 

    ```{R}
    # Generate plots from mothur sensspec files for comparing clustering algorithms.
    ```
---
### Best practices:

- Use `roxygen2`

---
## Activity

Let's document the [Riffomonas minimalR](https://github.com/riffomonas/minimalR) code:

1. module
1. dataset
1. functions
1. error message

---

### Instructions

1. Clone this repo
    ```{bash}
    git clone https://github.com/SchlossLab/documenting-R
    ```
1. Checkout a new branch
    ```{bash}
    git checkout -b descriptive-branch-name
    ```
1. After modifying your part, commit your changes
    ```{bash}
    git add .
    git commit -m "descriptive commit message"
    ```
1. Push your changes
    ```{bash}
    git push -u origin descriptive-branch-name
    ```
